version: "3.1"

services:
#  pub:
#    build: "./Publisher"
#    links:
#      - queue
#
#  sub:
#    build: "./Subscriber"
#    links:
#      - queue

  queue:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"